version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ../server/src
      dockerfile: ../../docker/server.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
      - DATABASE_URL=sqlite:///./crudai.db
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ../server/src:/app
      - ../server/src/crudai.db:/app/crudai.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web Service
  frontend:
    build:
      context: ../client
      dockerfile: ../docker/client.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
      - VITE_AUTH0_REDIRECT_URI=${VITE_AUTH0_REDIRECT_URI}
    volumes:
      - ../client:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  app_data: